vich_uploader:
    db_driver: orm

    mappings:
       article_thumbnails:
        #    uri_prefix: '%upload_dir%'
           upload_destination: '%uploads_dir%'
        #    upload_destination: '%kernel.project_dir%/public/%upload_dir%'
